# Generated by Django 4.1.7 on 2024-03-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_pathologylab_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hospitals',
            field=models.ManyToManyField(blank=True, related_name='services', to='home.hospital'),
        ),
        migrations.AlterField(
            model_name='service',
            name='pathology_labs',
            field=models.ManyToManyField(blank=True, related_name='services', to='home.pathologylab'),
        ),
    ]
