# Generated by Django 4.1.7 on 2024-03-09 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_service_image_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=15, unique=True)),
                ('message', models.TextField(max_length=500)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
