# Generated by Django 4.1.7 on 2024-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='zipcode',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pathologylab',
            name='zipcode',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
