# Generated by Django 4.1.7 on 2024-03-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_service_actual_price_service_discounted_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='my_price',
        ),
    ]
