# Generated by Django 5.0.3 on 2024-03-23 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_appointment_note_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Appointment_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
