# Generated by Django 5.0.3 on 2024-03-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='off_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
