# Generated by Django 5.0.3 on 2024-03-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_appointment_online_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_id',
            field=models.TextField(blank=True),
        ),
    ]
