# Generated by Django 5.0.3 on 2024-03-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_contact_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pathologylab',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
