# Generated by Django 5.0.3 on 2024-04-02 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_hospital_verified_pathologylab_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_kyc',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'is_hospital': True}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('owner_name', models.CharField(max_length=255)),
                ('id_proof', models.ImageField(upload_to='id_proofs/')),
            ],
        ),
        migrations.CreateModel(
            name='PathologyLab_kyc',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'is_pathology': True}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('owner_name', models.CharField(max_length=255)),
                ('id_proof', models.ImageField(upload_to='id_proofs/')),
            ],
        ),
    ]
