# Generated by Django 5.0.3 on 2024-04-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_hospital_kyc_pathologylab_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_kyc',
            name='id_proof_hospital',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs_hospital/'),
        ),
        migrations.AddField(
            model_name='pathologylab_kyc',
            name='id_proof_pathology',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs_pathology/'),
        ),
        migrations.AlterField(
            model_name='hospital_kyc',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AlterField(
            model_name='pathologylab_kyc',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs/'),
        ),
    ]
