# Generated by Django 5.0.3 on 2024-04-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_hospital_kyc_id_proof_hospital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_details',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
    ]
